### ISSUE TITLE
Native

### ISSUE THREAD

**Issue by pavelloz** [tolking/markdown-it-img-lazy#4]
Im afraid native mode doesnt work very well:

```
<img alt="Webfonts helper" data-src="..." loading="lazy" class="lazy">
```

It does not leave src="" intact, hence broking the image completely.

**Comment by tolking** [comment]
There will be no src after build.

It will be automatically modified when browsing according to browser support ([Lozad.js](https://github.com/ApoorvSaxena/lozad.js) and [imgLazy.js](https://github.com/tolking/markdown-it-img-lazy/blob/master/imgLazy.js))

Do you mean when after build

``` html
<img alt="Webfonts helper" src="..." loading="lazy" class="lazy">
```

**Comment by pavelloz** [comment]
Yes, i wanted src + loading="lazy" but i got data-src, which means image wont work without javascript (or in other words, natively).

**Comment by tolking** [comment]
Maybe the [markdown-it-image-lazy-loading](https://github.com/ruanyf/markdown-it-image-lazy-loading) is more suitable for your needs.

**Comment by tolking** [comment]
The purpose of this plug-in is to be compatible with unsupported browsers. Implementing this function will defeat the original purpose.

**Comment by pavelloz** [comment]
I think https://github.com/tolking/markdown-it-img-lazy#usenative is misleading then.

Anyway, i created [my own version](https://www.npmjs.com/package/markdown-it-lazyload) that does this, i just figured this is a bug so i reported it.
